################################################################################
#
# libarchive
#
################################################################################

LIBARCHIVE_VERSION = 3.7.2
LIBARCHIVE_SOURCE = libarchive-$(LIBARCHIVE_VERSION).tar.xz
LIBARCHIVE_SITE = https://www.libarchive.de/downloads
LIBARCHIVE_INSTALL_STAGING = YES
LIBARCHIVE_LICENSE = BSD-2-Clause, BSD-3-Clause, CC0-1.0, OpenSSL, Apache-2.0
LIBARCHIVE_LICENSE_FILES = COPYING
LIBARCHIVE_CPE_ID_VENDOR = libarchive
# We're patching configure.ac
LIBARCHIVE_AUTORECONF = YES
# needed for autoreconf
LIBARCHIVE_DEPENDENCIES += host-pkgconf

ifeq ($(BR2_PACKAGE_LIBARCHIVE_BSDTAR),y)
ifeq ($(BR2_STATIC_LIBS),y)
LIBARCHIVE_CONF_OPTS += -DENABLE_TAR_SHARED=OFF
else
LIBARCHIVE_CONF_OPTS += -DENABLE_TAR_SHARED=ON
endif
else
LIBARCHIVE_CONF_OPTS += -DENABLE_TAR=OFF
endif

ifeq ($(BR2_PACKAGE_LIBARCHIVE_BSDCPIO),y)
ifeq ($(BR2_STATIC_LIBS),y)
LIBARCHIVE_CONF_OPTS += -DENABLE_CPIO_SHARED=OFF
else
LIBARCHIVE_CONF_OPTS += -DENABLE_CPIO_SHARED=ON
endif
else
LIBARCHIVE_CONF_OPTS += -DENABLE_CPIO=OFF
endif

ifeq ($(BR2_PACKAGE_LIBARCHIVE_BSDCAT),y)
ifeq ($(BR2_STATIC_LIBS),y)
LIBARCHIVE_CONF_OPTS += -DENABLE_CAT_SHARED=OFF
else
LIBARCHIVE_CONF_OPTS += -DENABLE_CAT_SHARED=ON
endif
else
LIBARCHIVE_CONF_OPTS += -DENABLE_CAT=OFF
endif

ifeq ($(BR2_PACKAGE_ACL),y)
LIBARCHIVE_DEPENDENCIES += acl
else
LIBARCHIVE_CONF_OPTS += --disable-acl
endif

ifeq ($(BR2_PACKAGE_ATTR),y)
LIBARCHIVE_DEPENDENCIES += attr
else
LIBARCHIVE_CONF_OPTS += -DENABLE_ACL=OFF
endif

ifeq ($(BR2_PACKAGE_BZIP2),y)
LIBARCHIVE_CONF_OPTS += -DENABLE_BZip2=ON
LIBARCHIVE_DEPENDENCIES += bzip2
else
LIBARCHIVE_CONF_OPTS += -DENABLE_BZip2=OFF
endif

ifeq ($(BR2_PACKAGE_EXPAT),y)
LIBARCHIVE_DEPENDENCIES += expat
else
LIBARCHIVE_CONF_OPTS += -DENABLE_EXPAT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBICONV),y)
LIBARCHIVE_DEPENDENCIES += libiconv
else
LIBARCHIVE_CONF_OPTS += -DENABLE_ICONV=OFF
endif

ifeq ($(BR2_PACKAGE_LIBXML2),y)
LIBARCHIVE_DEPENDENCIES += libxml2
LIBARCHIVE_CONF_ENV += XML2_CONFIG=$(STAGING_DIR)/usr/bin/xml2-config
else
LIBARCHIVE_CONF_OPTS += -DENABLE_LIBXML2=OFF
endif

ifeq ($(BR2_PACKAGE_LZ4),y)
LIBARCHIVE_CONF_OPTS += -DENABLE_LZ4=ON
LIBARCHIVE_DEPENDENCIES += lz4
else
LIBARCHIVE_CONF_OPTS += -DENABLE_LZ4=OFF
endif

ifeq ($(BR2_PACKAGE_LZO),y)
LIBARCHIVE_DEPENDENCIES += lzo
else
LIBARCHIVE_CONF_OPTS += -DENABLE_LZO=OFF
endif

ifeq ($(BR2_PACKAGE_MBEDTLS),y)
LIBARCHIVE_DEPENDENCIES += mbedtls
LIBARCHIVE_CONF_OPTS += -DENABLE_MBEDTLS=ON
else
LIBARCHIVE_CONF_OPTS += -DENABLE_MBEDTLS=OFF
endif

ifeq ($(BR2_PACKAGE_NETTLE),y)
LIBARCHIVE_DEPENDENCIES += nettle
LIBARCHIVE_CONF_OPTS += -DENABLE_NETTLE=ON
else
LIBARCHIVE_CONF_OPTS += -DENABLE_NETTLE=OFF
endif

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBARCHIVE_DEPENDENCIES += openssl
else
LIBARCHIVE_CONF_OPTS += -DENABLE_OPENSSL=OFF
endif

ifeq ($(BR2_PACKAGE_ZLIB),y)
LIBARCHIVE_DEPENDENCIES += zlib
else
LIBARCHIVE_CONF_OPTS += -DENABLE_ZLIB=OFF
endif

# libarchive requires LZMA with thread support in the toolchain
ifeq ($(BR2_TOOLCHAIN_HAS_THREADS)$(BR2_PACKAGE_XZ),yy)
LIBARCHIVE_DEPENDENCIES += xz
LIBARCHIVE_CONF_OPTS += -DENABLE_LZMA=ON
else
LIBARCHIVE_CONF_OPTS += -DENABLE_LZMA=OFF
endif

ifeq ($(BR2_PACKAGE_ZSTD),y)
LIBARCHIVE_DEPENDENCIES += zstd
LIBARCHIVE_CONF_OPTS += -DENABLE_ZSTD=ON
else
LIBARCHIVE_CONF_OPTS += -DENABLE_ZSTD=OFF
endif

# The only user of host-libarchive needs zlib support
HOST_LIBARCHIVE_DEPENDENCIES = host-zlib
# needed for autoreconf
HOST_LIBARCHIVE_DEPENDENCIES += host-pkgconf
HOST_LIBARCHIVE_CONF_OPTS = \
	-DENABLE_TAR=OFF
	-DENABLE_CPIO=OFF
	-DENABLE_CAT=OFF
	-DENABLE_MBEDTLS=OFF
	-DENABLE_NETTLE=OFF
	-DENABLE_OPENSSL=OFF
	-DENABLE_LIBB2=OFF
	-DENABLE_LZ4=OFF
	-DENABLE_LZO=OFF
	-DENABLE_LZMA=OFF
	-DENABLE_ZSTD=OFF
	-DENABLE_BZip2=OFF
	-DENABLE_LIBXML2=OFF
	-DENABLE_EXPAT=OFF
	-DENABLE_XATTR=OFF
	-DENABLE_ACL=OFF
	-DENABLE_ICONV=OFF
	-DENABLE_TEST=OFF
$(eval $(cmake-package))
$(eval $(host-cmake-package))
