################################################################################
#
# vulkan-tools
#
################################################################################

VULKAN_TOOLS_VERSION = 02e70b9b4ad86e8db43d5f8dfc62edab0ddb4020
VULKAN_TOOLS_SITE = $(call github,KhronosGroup,Vulkan-Tools,$(VULKAN_TOOLS_VERSION))
VULKAN_TOOLS_LICENSE = Apache-2.0
VULKAN_TOOLS_LICENSE_FILES = LICENSE.txt
VULKAN_TOOLS_INSTALL_STAGING = YES
VULKAN_TOOLS_SUPPORTS_IN_SOURCE_BUILD = NO

VULKAN_TOOLS_DEPENDENCIES = \
	vulkan-headers \
	vulkan-loader \
	host-python3 \
	host-glslang \
	wayland \
	vulkan-volk

ifeq ($(BR2_PACKAGE_MESA3D),y)
VULKAN_TOOLS_DEPENDENCIES += mesa3d
endif

VULKAN_TOOLS_CONF_OPTS += \
	-DBUILD_CUBE=OFF \
	-DVULKAN_HEADERS_INSTALL_DIR="$(STAGING_DIR)/usr/include/" \
	-DBUILD_SHARED_LIBS=OFF

VULKAN_TOOLS_CONF_ENV += LDFLAGS="-lpthread -ldl"

ifeq ($(BR2_PACKAGE_DIRECTFB),y)
VULKAN_TOOLS_DEPENDENCIES += directfb
VULKAN_TOOLS_CONF_OPTS += -DBUILD_WSI_DIRECTFB_SUPPORT=ON
else
VULKAN_TOOLS_CONF_OPTS += -DBUILD_WSI_DIRECTFB_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBXCB),y)
VULKAN_TOOLS_DEPENDENCIES += libxcb
VULKAN_TOOLS_CONF_OPTS += \
	-DBUILD_WSI_XCB_SUPPORT=ON \
	-DBUILD_WSI_XLIB_SUPPORT=ON
else
VULKAN_TOOLS_CONF_OPTS += \
	-DBUILD_WSI_XCB_SUPPORT=OFF \
	-DBUILD_WSI_XLIB_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_WAYLAND),y)
VULKAN_TOOLS_DEPENDENCIES += wayland
VULKAN_TOOLS_CONF_OPTS += -DBUILD_WSI_WAYLAND_SUPPORT=ON
else
VULKAN_TOOLS_CONF_OPTS += -DBUILD_WSI_WAYLAND_SUPPORT=OFF
endif

$(eval $(cmake-package))
