################################################################################
#
# qt6shadertools
#
################################################################################

QT6SHADERTOOLS_VERSION = $(QT6_VERSION)
QT6SHADERTOOLS_SITE = $(QT6_SITE)
QT6SHADERTOOLS_SOURCE = qtshadertools-$(QT6_SOURCE_TARBALL_PREFIX)-$(QT6SHADERTOOLS_VERSION).tar.xz
QT6SHADERTOOLS_INSTALL_STAGING = YES
QT6SHADERTOOLS_SUPPORTS_IN_SOURCE_BUILD = NO

QT6SHADERTOOLS_LICENSE = \
	GPL-2.0+ or LGPL-3.0, \
	GPL-3.0 with exception (tools), \
	GFDL-1.3 (docs), \
	BSD-3-Clause

QT6SHADERTOOLS_LICENSE_FILES = \
	LICENSES/BSD-3-Clause.txt \
	LICENSES/GFDL-1.3-no-invariants-only.txt \
	LICENSES/GPL-2.0-only.txt \
	LICENSES/GPL-3.0-only.txt \
	LICENSES/LGPL-3.0-only.txt \
	LICENSES/Qt-GPL-exception-1.0.txt

HOST_QT6SHADERTOOLS_DEPENDENCIES = \
	host-qt6base
	
HOST_QT6SHADERTOOLS_CONF_OPTS = \
	-GNinja \
	$(QT6_COMMON_CONF_OPTS)

define HOST_QT6SHADERTOOLS_BUILD_CMDS
	$(HOST_MAKE_ENV) $(BR2_CMAKE) --build $(HOST_QT6SHADERTOOLS_BUILDDIR)
endef

define HOST_QT6SHADERTOOLS_INSTALL_CMDS
	$(HOST_MAKE_ENV) $(BR2_CMAKE) --install $(HOST_QT6SHADERTOOLS_BUILDDIR)
endef

QT6SHADERTOOLS_CONF_OPTS = \
	-GNinja \
	-DQT_HOST_PATH=$(HOST_DIR) \
	$(QT6_COMMON_CONF_OPTS)

QT6SHADERTOOLS_DEPENDENCIES = \
	host-pkgconf \
	host-ninja \
	qt6base \
	host-qt6shadertools

define QT6SHADERTOOLS_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(BR2_CMAKE) --build $(QT6SHADERTOOLS_BUILDDIR)
endef

define QT6SHADERTOOLS_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) DESTDIR=$(STAGING_DIR) $(BR2_CMAKE) --install $(QT6SHADERTOOLS_BUILDDIR)
endef

define QT6SHADERTOOLS_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) DESTDIR=$(TARGET_DIR) $(BR2_CMAKE) --install $(QT6SHADERTOOLS_BUILDDIR)
endef

$(eval $(cmake-package))
$(eval $(host-cmake-package))

